import js from '@eslint/js';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import tseslint from '@typescript-eslint/eslint-plugin';
import tsparser from '@typescript-eslint/parser';

export default [
  {
    ignores: ['dist', 'node_modules', '.next', '.vite'],
  },
  {
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      ecmaVersion: 2020,
      globals: {
        console: 'readonly',
        process: 'readonly',
        Buffer: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        global: 'readonly',
        // Browser globals
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        location: 'readonly',
        history: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        fetch: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        FormData: 'readonly',
        Blob: 'readonly',
        File: 'readonly',
        FileReader: 'readonly',
        WebSocket: 'readonly',
        Worker: 'readonly',
        MutationObserver: 'readonly',
        ResizeObserver: 'readonly',
        IntersectionObserver: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        queueMicrotask: 'readonly',
        // DOM types
        HTMLElement: 'readonly',
        HTMLDivElement: 'readonly',
        HTMLButtonElement: 'readonly',
        HTMLInputElement: 'readonly',
        HTMLTextAreaElement: 'readonly',
        HTMLSelectElement: 'readonly',
        HTMLFormElement: 'readonly',
        HTMLAnchorElement: 'readonly',
        HTMLImageElement: 'readonly',
        HTMLVideoElement: 'readonly',
        HTMLAudioElement: 'readonly',
        HTMLCanvasElement: 'readonly',
        HTMLSpanElement: 'readonly',
        HTMLParagraphElement: 'readonly',
        HTMLHeadingElement: 'readonly',
        HTMLTableElement: 'readonly',
        HTMLTableSectionElement: 'readonly',
        HTMLTableRowElement: 'readonly',
        HTMLTableCellElement: 'readonly',
        HTMLTableCaptionElement: 'readonly',
        SVGElement: 'readonly',
        Element: 'readonly',
        Node: 'readonly',
        NodeList: 'readonly',
        Document: 'readonly',
        Window: 'readonly',
        Event: 'readonly',
        MouseEvent: 'readonly',
        KeyboardEvent: 'readonly',
        TouchEvent: 'readonly',
        PointerEvent: 'readonly',
        FocusEvent: 'readonly',
        InputEvent: 'readonly',
        WheelEvent: 'readonly',
        DragEvent: 'readonly',
        ClipboardEvent: 'readonly',
        MessageEvent: 'readonly',
        ErrorEvent: 'readonly',
        PromiseRejectionEvent: 'readonly',
        CustomEvent: 'readonly',
        EventTarget: 'readonly',
        AbortController: 'readonly',
        AbortSignal: 'readonly',
        DOMException: 'readonly',
        DOMParser: 'readonly',
        XMLSerializer: 'readonly',
        Range: 'readonly',
        Selection: 'readonly',
        MediaQueryList: 'readonly',
        CSSStyleDeclaration: 'readonly',
        // JSX namespace
        JSX: 'readonly',
        // React (used as namespace in some JSX transforms)
        React: 'readonly',
        // Additional DOM types
        DOMRect: 'readonly',
        DOMRectReadOnly: 'readonly',
        DOMMatrix: 'readonly',
        DOMPoint: 'readonly',
        HTMLLinkElement: 'readonly',
        HTMLScriptElement: 'readonly',
        HTMLStyleElement: 'readonly',
        HTMLMetaElement: 'readonly',
        HTMLTitleElement: 'readonly',
        HTMLBodyElement: 'readonly',
        HTMLHeadElement: 'readonly',
        HTMLIFrameElement: 'readonly',
        HTMLObjectElement: 'readonly',
        HTMLEmbedElement: 'readonly',
        HTMLLabelElement: 'readonly',
        HTMLFieldSetElement: 'readonly',
        HTMLLegendElement: 'readonly',
        HTMLOutputElement: 'readonly',
        HTMLProgressElement: 'readonly',
        HTMLMeterElement: 'readonly',
        HTMLDetailsElement: 'readonly',
        HTMLDialogElement: 'readonly',
        HTMLMenuElement: 'readonly',
        HTMLOListElement: 'readonly',
        HTMLUListElement: 'readonly',
        HTMLLIElement: 'readonly',
        HTMLPreElement: 'readonly',
        HTMLQuoteElement: 'readonly',
        HTMLHRElement: 'readonly',
        HTMLBRElement: 'readonly',
        HTMLModElement: 'readonly',
        HTMLTimeElement: 'readonly',
        HTMLDataElement: 'readonly',
        HTMLSlotElement: 'readonly',
        HTMLTemplateElement: 'readonly',
        HTMLUnknownElement: 'readonly',
        HTMLCollection: 'readonly',
        HTMLAllCollection: 'readonly',
        // Additional event types
        PopStateEvent: 'readonly',
        HashChangeEvent: 'readonly',
        StorageEvent: 'readonly',
        BeforeUnloadEvent: 'readonly',
        PageTransitionEvent: 'readonly',
        TransitionEvent: 'readonly',
        AnimationEvent: 'readonly',
        GamepadEvent: 'readonly',
        DeviceMotionEvent: 'readonly',
        DeviceOrientationEvent: 'readonly',
        SecurityPolicyViolationEvent: 'readonly',
        SubmitEvent: 'readonly',
        ToggleEvent: 'readonly',
        MessageEventSource: 'readonly',
        // Additional browser APIs
        getComputedStyle: 'readonly',
        matchMedia: 'readonly',
        getSelection: 'readonly',
        scrollTo: 'readonly',
        scrollBy: 'readonly',
        scroll: 'readonly',
        open: 'readonly',
        close: 'readonly',
        focus: 'readonly',
        blur: 'readonly',
        print: 'readonly',
        alert: 'readonly',
        confirm: 'readonly',
        prompt: 'readonly',
        postMessage: 'readonly',
        requestIdleCallback: 'readonly',
        cancelIdleCallback: 'readonly',
        structuredClone: 'readonly',
        crypto: 'readonly',
        performance: 'readonly',
        screen: 'readonly',
        visualViewport: 'readonly',
        // Testing library globals
        fireEvent: 'readonly',
        render: 'readonly',
        screen: 'readonly',
        waitFor: 'readonly',
        act: 'readonly',
        // Node.js additional
        setImmediate: 'readonly',
        clearImmediate: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        atob: 'readonly',
        btoa: 'readonly',
      },
      parser: tsparser,
      parserOptions: {
        ecmaVersion: 'latest',
        ecmaFeatures: { jsx: true },
        sourceType: 'module',
      },
    },
    plugins: {
      '@typescript-eslint': tseslint,
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    rules: {
      ...js.configs.recommended.rules,
      ...tseslint.configs.recommended.rules,
      ...reactHooks.configs.recommended.rules,
      'react-refresh/only-export-components': [
        'warn',
        { allowConstantExport: true },
      ],
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_|^error$|^err$|^e$' }],
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/explicit-function-return-type': 'off',
      '@typescript-eslint/explicit-module-boundary-types': 'off',
      '@typescript-eslint/no-empty-function': 'off',
      'prefer-const': 'error',
      'no-var': 'error',
    },
  },
];
