import js from '@eslint/js';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import tseslint from '@typescript-eslint/eslint-plugin';
import tsparser from '@typescript-eslint/parser';

// ── Shared browser + Node globals ─────────────────────────────────────────────
// ESLint's no-undef rule fires for any identifier not in this list.
// We list every browser/DOM/Node global used across the codebase so the rule
// catches real typos without drowning in false positives.
const sharedGlobals = {
  // Node built-ins
  console: 'readonly',
  process: 'readonly',
  Buffer: 'readonly',
  __dirname: 'readonly',
  __filename: 'readonly',
  global: 'readonly',
  require: 'readonly',
  module: 'readonly',
  exports: 'readonly',
  setInterval: 'readonly',
  clearInterval: 'readonly',
  setTimeout: 'readonly',
  clearTimeout: 'readonly',
  setImmediate: 'readonly',
  clearImmediate: 'readonly',
  queueMicrotask: 'readonly',
  URL: 'readonly',
  URLSearchParams: 'readonly',
  AbortController: 'readonly',
  AbortSignal: 'readonly',
  fetch: 'readonly',
  FormData: 'readonly',
  File: 'readonly',
  Blob: 'readonly',
  Request: 'readonly',
  Response: 'readonly',
  Headers: 'readonly',
  RequestInit: 'readonly',
  TextEncoder: 'readonly',
  TextDecoder: 'readonly',
  crypto: 'readonly',
  performance: 'readonly',
  structuredClone: 'readonly',

  // Browser / DOM
  window: 'readonly',
  document: 'readonly',
  navigator: 'readonly',
  location: 'readonly',
  history: 'readonly',
  localStorage: 'readonly',
  sessionStorage: 'readonly',
  requestAnimationFrame: 'readonly',
  cancelAnimationFrame: 'readonly',
  requestIdleCallback: 'readonly',
  cancelIdleCallback: 'readonly',
  getComputedStyle: 'readonly',
  matchMedia: 'readonly',
  alert: 'readonly',
  confirm: 'readonly',
  prompt: 'readonly',
  open: 'readonly',
  close: 'readonly',
  atob: 'readonly',
  btoa: 'readonly',
  Image: 'readonly',

  // DOM event / observer types
  Event: 'readonly',
  CustomEvent: 'readonly',
  KeyboardEvent: 'readonly',
  MouseEvent: 'readonly',
  MessageEvent: 'readonly',
  PopStateEvent: 'readonly',
  EventSource: 'readonly',
  WebSocket: 'readonly',
  MutationObserver: 'readonly',
  IntersectionObserver: 'readonly',
  ResizeObserver: 'readonly',
  PerformanceObserver: 'readonly',
  EventListener: 'readonly',
  EventTarget: 'readonly',
  XMLHttpRequest: 'readonly',

  // DOM element types
  HTMLElement: 'readonly',
  HTMLDivElement: 'readonly',
  HTMLButtonElement: 'readonly',
  HTMLInputElement: 'readonly',
  HTMLSpanElement: 'readonly',
  HTMLParagraphElement: 'readonly',
  HTMLHeadingElement: 'readonly',
  HTMLTableElement: 'readonly',
  HTMLTableSectionElement: 'readonly',
  HTMLTableRowElement: 'readonly',
  HTMLTableCellElement: 'readonly',
  HTMLTableCaptionElement: 'readonly',
  HTMLAnchorElement: 'readonly',
  HTMLImageElement: 'readonly',
  HTMLVideoElement: 'readonly',
  HTMLAudioElement: 'readonly',
  HTMLCanvasElement: 'readonly',
  HTMLStyleElement: 'readonly',
  HTMLTextAreaElement: 'readonly',
  HTMLSelectElement: 'readonly',
  HTMLFormElement: 'readonly',
  HTMLOListElement: 'readonly',
  HTMLUListElement: 'readonly',
  HTMLLIElement: 'readonly',
  HTMLIFrameElement: 'readonly',
  HTMLScriptElement: 'readonly',
  HTMLMetaElement: 'readonly',
  HTMLLinkElement: 'readonly',
  HTMLTitleElement: 'readonly',
  SVGElement: 'readonly',
  SVGSVGElement: 'readonly',
  Element: 'readonly',
  Node: 'readonly',
  NodeList: 'readonly',
  DocumentFragment: 'readonly',
  ShadowRoot: 'readonly',
  Range: 'readonly',
  Selection: 'readonly',
  FileList: 'readonly',
  FileReader: 'readonly',
  DOMParser: 'readonly',
  DOMRect: 'readonly',
  DOMRectReadOnly: 'readonly',
  CSSStyleDeclaration: 'readonly',

  // React (JSX transform — React 17+ doesn't need explicit import)
  React: 'readonly',
};

export default [
  {
    ignores: ['dist', 'dist-electron', 'node_modules', '.next', '.vite', 'dev-tools', 'source-mapper', 'airo-secrets', 'electron'],
  },
  {
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      ecmaVersion: 2022,
      globals: sharedGlobals,
      parser: tsparser,
      parserOptions: {
        ecmaVersion: 'latest',
        ecmaFeatures: { jsx: true },
        sourceType: 'module',
      },
    },
    plugins: {
      '@typescript-eslint': tseslint,
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    rules: {
      ...js.configs.recommended.rules,
      ...tseslint.configs.recommended.rules,
      ...reactHooks.configs.recommended.rules,
      'react-refresh/only-export-components': [
        'warn',
        { allowConstantExport: true },
      ],
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/explicit-function-return-type': 'off',
      '@typescript-eslint/explicit-module-boundary-types': 'off',
      '@typescript-eslint/no-empty-function': 'off',
      '@typescript-eslint/no-require-imports': 'off', // CJS interop via createRequire is intentional
      'prefer-const': 'error',
      'no-var': 'error',
      'no-undef': 'off', // TypeScript's type checker handles undefined references more accurately
    },
  },
];
