/**
 * GET /api/demo
 *
 * Returns a set of realistic mock MediaItem objects so the Airo builder
 * preview can render the full HomeStream UI without a real media library.
 *
 * This endpoint is ONLY used by the builder preview — production installs
 * with a real library never call it (MediaContext skips it when library > 0).
 */
import type { Request, Response } from 'express';

const daysAgo = (n: number) => new Date(Date.now() - n * 86400000).toISOString();

const DEMO_ITEMS = [
  // ── Movies ────────────────────────────────────────────────────────────────
  {
    id: 'demo-1',
    imdbId: 'tt4154796',
    filename: 'Avengers.Endgame.2019.1080p.mkv',
    filepath: '/demo/Avengers.Endgame.2019.1080p.mkv',
    title: 'Avengers: Endgame',
    year: '2019',
    genre: ['Action', 'Adventure', 'Sci-Fi'],
    plot: 'After the devastating events of Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more to reverse Thanos\'s actions and restore balance to the universe.',
    director: 'Anthony Russo, Joe Russo',
    actors: 'Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth',
    imdbRating: '8.4',
    poster: 'https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg',
    type: 'movie',
    runtime: '181 min',
    rated: 'PG-13',
    addedAt: daysAgo(2),
    watchProgress: 65,
    watchedSeconds: 7100,
    totalSeconds: 10860,
    lastWatchedAt: daysAgo(1),
    fileSize: 12884901888,
  },
  {
    id: 'demo-2',
    imdbId: 'tt1375666',
    filename: 'Inception.2010.1080p.mkv',
    filepath: '/demo/Inception.2010.1080p.mkv',
    title: 'Inception',
    year: '2010',
    genre: ['Action', 'Sci-Fi', 'Thriller'],
    plot: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    director: 'Christopher Nolan',
    actors: 'Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page, Tom Hardy',
    imdbRating: '8.8',
    poster: 'https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg',
    type: 'movie',
    runtime: '148 min',
    rated: 'PG-13',
    addedAt: daysAgo(5),
    watchProgress: 100,
    watchedSeconds: 8880,
    totalSeconds: 8880,
    watchedAt: daysAgo(3),
    fileSize: 9663676416,
  },
  {
    id: 'demo-3',
    imdbId: 'tt0816692',
    filename: 'Interstellar.2014.4K.mkv',
    filepath: '/demo/Interstellar.2014.4K.mkv',
    title: 'Interstellar',
    year: '2014',
    genre: ['Adventure', 'Drama', 'Sci-Fi'],
    plot: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
    director: 'Christopher Nolan',
    actors: 'Matthew McConaughey, Anne Hathaway, Jessica Chastain, Michael Caine',
    imdbRating: '8.7',
    poster: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    type: 'movie',
    runtime: '169 min',
    rated: 'PG',
    addedAt: daysAgo(7),
    watchProgress: 0,
    watchedSeconds: 0,
    totalSeconds: 10140,
    fileSize: 21474836480,
  },
  {
    id: 'demo-4',
    imdbId: 'tt0468569',
    filename: 'The.Dark.Knight.2008.1080p.mkv',
    filepath: '/demo/The.Dark.Knight.2008.1080p.mkv',
    title: 'The Dark Knight',
    year: '2008',
    genre: ['Action', 'Crime', 'Drama'],
    plot: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
    director: 'Christopher Nolan',
    actors: 'Christian Bale, Heath Ledger, Aaron Eckhart, Michael Caine',
    imdbRating: '9.0',
    poster: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    type: 'movie',
    runtime: '152 min',
    rated: 'PG-13',
    addedAt: daysAgo(10),
    watchProgress: 30,
    watchedSeconds: 2736,
    totalSeconds: 9120,
    lastWatchedAt: daysAgo(4),
    fileSize: 10737418240,
  },
  {
    id: 'demo-5',
    imdbId: 'tt6751668',
    filename: 'Parasite.2019.1080p.mkv',
    filepath: '/demo/Parasite.2019.1080p.mkv',
    title: 'Parasite',
    year: '2019',
    genre: ['Comedy', 'Drama', 'Thriller'],
    plot: 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
    director: 'Bong Joon Ho',
    actors: 'Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong, Choi Woo-shik',
    imdbRating: '8.5',
    poster: 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
    type: 'movie',
    runtime: '132 min',
    rated: 'R',
    addedAt: daysAgo(14),
    watchProgress: 0,
    watchedSeconds: 0,
    totalSeconds: 7920,
    fileSize: 8053063680,
  },
  {
    id: 'demo-6',
    imdbId: 'tt0110912',
    filename: 'Pulp.Fiction.1994.1080p.mkv',
    filepath: '/demo/Pulp.Fiction.1994.1080p.mkv',
    title: 'Pulp Fiction',
    year: '1994',
    genre: ['Crime', 'Drama'],
    plot: 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
    director: 'Quentin Tarantino',
    actors: 'John Travolta, Uma Thurman, Samuel L. Jackson, Bruce Willis',
    imdbRating: '8.9',
    poster: 'https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
    type: 'movie',
    runtime: '154 min',
    rated: 'R',
    addedAt: daysAgo(20),
    watchProgress: 100,
    watchedSeconds: 9240,
    totalSeconds: 9240,
    watchedAt: daysAgo(10),
    fileSize: 9126805504,
  },
  {
    id: 'demo-7',
    imdbId: 'tt0245429',
    filename: 'Spirited.Away.2001.1080p.mkv',
    filepath: '/demo/Spirited.Away.2001.1080p.mkv',
    title: 'Spirited Away',
    year: '2001',
    genre: ['Animation', 'Adventure', 'Family'],
    plot: 'During her family\'s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.',
    director: 'Hayao Miyazaki',
    actors: 'Daveigh Chase, Suzanne Pleshette, Miyu Irino, Rumi Hiiragi',
    imdbRating: '8.6',
    poster: 'https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
    type: 'movie',
    runtime: '125 min',
    rated: 'PG',
    addedAt: daysAgo(25),
    watchProgress: 0,
    watchedSeconds: 0,
    totalSeconds: 7500,
    fileSize: 7516192768,
  },
  {
    id: 'demo-8',
    imdbId: 'tt1853728',
    filename: 'Django.Unchained.2012.1080p.mkv',
    filepath: '/demo/Django.Unchained.2012.1080p.mkv',
    title: 'Django Unchained',
    year: '2012',
    genre: ['Drama', 'Western'],
    plot: 'With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.',
    director: 'Quentin Tarantino',
    actors: 'Jamie Foxx, Christoph Waltz, Leonardo DiCaprio, Kerry Washington',
    imdbRating: '8.4',
    poster: 'https://image.tmdb.org/t/p/w500/7oWY8VDWW7thTzWh3OKYRkWAKdN.jpg',
    type: 'movie',
    runtime: '165 min',
    rated: 'R',
    addedAt: daysAgo(30),
    watchProgress: 0,
    watchedSeconds: 0,
    totalSeconds: 9900,
    fileSize: 11274289152,
  },
  // ── TV Shows ──────────────────────────────────────────────────────────────
  {
    id: 'demo-9',
    imdbId: 'tt0903747',
    filename: 'Breaking.Bad.S01E01.1080p.mkv',
    filepath: '/demo/Breaking.Bad.S01E01.1080p.mkv',
    title: 'Breaking Bad',
    year: '2008',
    genre: ['Crime', 'Drama', 'Thriller'],
    plot: 'A chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine with a former student to secure his family\'s future.',
    director: 'Vince Gilligan',
    actors: 'Bryan Cranston, Aaron Paul, Anna Gunn, Dean Norris',
    imdbRating: '9.5',
    poster: 'https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg',
    type: 'series',
    runtime: '47 min',
    rated: 'TV-MA',
    addedAt: daysAgo(3),
    watchProgress: 45,
    watchedSeconds: 1270,
    totalSeconds: 2820,
    lastWatchedAt: daysAgo(1),
    fileSize: 3221225472,
  },
  {
    id: 'demo-10',
    imdbId: 'tt0944947',
    filename: 'Game.of.Thrones.S01E01.1080p.mkv',
    filepath: '/demo/Game.of.Thrones.S01E01.1080p.mkv',
    title: 'Game of Thrones',
    year: '2011',
    genre: ['Action', 'Adventure', 'Drama'],
    plot: 'Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.',
    director: 'David Benioff, D.B. Weiss',
    actors: 'Emilia Clarke, Peter Dinklage, Kit Harington, Lena Headey',
    imdbRating: '9.2',
    poster: 'https://image.tmdb.org/t/p/w500/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg',
    type: 'series',
    runtime: '57 min',
    rated: 'TV-MA',
    addedAt: daysAgo(8),
    watchProgress: 100,
    watchedSeconds: 3420,
    totalSeconds: 3420,
    watchedAt: daysAgo(5),
    fileSize: 4294967296,
  },
  {
    id: 'demo-11',
    imdbId: 'tt4574334',
    filename: 'Stranger.Things.S01E01.1080p.mkv',
    filepath: '/demo/Stranger.Things.S01E01.1080p.mkv',
    title: 'Stranger Things',
    year: '2016',
    genre: ['Drama', 'Fantasy', 'Horror'],
    plot: 'When a young boy disappears, his mother, a police chief and his friends must confront terrifying supernatural forces in order to get him back.',
    director: 'Matt Duffer, Ross Duffer',
    actors: 'Millie Bobby Brown, Finn Wolfhard, Winona Ryder, David Harbour',
    imdbRating: '8.7',
    poster: 'https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg',
    type: 'series',
    runtime: '51 min',
    rated: 'TV-14',
    addedAt: daysAgo(12),
    watchProgress: 20,
    watchedSeconds: 612,
    totalSeconds: 3060,
    lastWatchedAt: daysAgo(6),
    fileSize: 3758096384,
  },
  {
    id: 'demo-12',
    imdbId: 'tt2861424',
    filename: 'Rick.and.Morty.S01E01.1080p.mkv',
    filepath: '/demo/Rick.and.Morty.S01E01.1080p.mkv',
    title: 'Rick and Morty',
    year: '2013',
    genre: ['Animation', 'Adventure', 'Comedy'],
    plot: 'An animated series that follows the exploits of a super scientist and his not-so-bright grandson.',
    director: 'Justin Roiland, Dan Harmon',
    actors: 'Justin Roiland, Chris Parnell, Spencer Grammer, Sarah Chalke',
    imdbRating: '9.1',
    poster: 'https://image.tmdb.org/t/p/w500/cvhNj9eoRBe5SxjCbQTkh05UP5K.jpg',
    type: 'series',
    runtime: '23 min',
    rated: 'TV-14',
    addedAt: daysAgo(15),
    watchProgress: 0,
    watchedSeconds: 0,
    totalSeconds: 1380,
    fileSize: 1073741824,
  },
];

export default function handler(_req: Request, res: Response) {
  res.json(DEMO_ITEMS);
}
