/**
 * GET /api/demo
 *
 * Returns a set of realistic mock MediaItem objects so the Airo builder
 * preview can render the full HomeStream UI without a real media library.
 *
 * Includes:
 *  - 10 movies across Action, Sci-Fi, Crime, Drama, Horror, Romance, Comedy, Animation genres
 *  - 3 TV shows with full S01 episode lists so the player "next episode" flow works
 *
 * This endpoint is ONLY used by the builder preview — production installs
 * with a real library never call it (MediaContext skips it when library > 0).
 */
import type { Request, Response } from 'express';

const daysAgo = (n: number) => new Date(Date.now() - n * 86400000).toISOString();

const DEMO_ITEMS = [
  // ── Movies ────────────────────────────────────────────────────────────────

  // Action / Adventure
  {
    id: 'demo-1',
    imdbId: 'tt4154796',
    filename: 'Avengers.Endgame.2019.1080p.mkv',
    filepath: '/demo/Avengers.Endgame.2019.1080p.mkv',
    title: 'Avengers: Endgame',
    year: '2019',
    genre: ['Action', 'Adventure', 'Sci-Fi'],
    plot: 'After the devastating events of Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more to reverse Thanos\'s actions and restore balance to the universe.',
    director: 'Anthony Russo, Joe Russo',
    actors: 'Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth',
    imdbRating: '8.4',
    poster: 'https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg',
    type: 'movie',
    runtime: '181 min',
    rated: 'PG-13',
    addedAt: daysAgo(2),
    watchProgress: 65,
    watchedSeconds: 7100,
    totalSeconds: 10860,
    lastWatchedAt: daysAgo(1),
    fileSize: 12884901888,
  },

  // Sci-Fi / Thriller
  {
    id: 'demo-2',
    imdbId: 'tt1375666',
    filename: 'Inception.2010.1080p.mkv',
    filepath: '/demo/Inception.2010.1080p.mkv',
    title: 'Inception',
    year: '2010',
    genre: ['Action', 'Sci-Fi', 'Thriller'],
    plot: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    director: 'Christopher Nolan',
    actors: 'Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page, Tom Hardy',
    imdbRating: '8.8',
    poster: 'https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg',
    type: 'movie',
    runtime: '148 min',
    rated: 'PG-13',
    addedAt: daysAgo(5),
    watchProgress: 100,
    watchedSeconds: 8880,
    totalSeconds: 8880,
    watchedAt: daysAgo(3),
    fileSize: 9663676416,
  },

  // Adventure / Drama / Sci-Fi
  {
    id: 'demo-3',
    imdbId: 'tt0816692',
    filename: 'Interstellar.2014.4K.mkv',
    filepath: '/demo/Interstellar.2014.4K.mkv',
    title: 'Interstellar',
    year: '2014',
    genre: ['Adventure', 'Drama', 'Sci-Fi'],
    plot: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
    director: 'Christopher Nolan',
    actors: 'Matthew McConaughey, Anne Hathaway, Jessica Chastain, Michael Caine',
    imdbRating: '8.7',
    poster: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    type: 'movie',
    runtime: '169 min',
    rated: 'PG',
    addedAt: daysAgo(7),
    watchProgress: 0,
    watchedSeconds: 0,
    totalSeconds: 10140,
    fileSize: 21474836480,
  },

  // Action / Crime / Drama
  {
    id: 'demo-4',
    imdbId: 'tt0468569',
    filename: 'The.Dark.Knight.2008.1080p.mkv',
    filepath: '/demo/The.Dark.Knight.2008.1080p.mkv',
    title: 'The Dark Knight',
    year: '2008',
    genre: ['Action', 'Crime', 'Drama'],
    plot: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
    director: 'Christopher Nolan',
    actors: 'Christian Bale, Heath Ledger, Aaron Eckhart, Michael Caine',
    imdbRating: '9.0',
    poster: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    type: 'movie',
    runtime: '152 min',
    rated: 'PG-13',
    addedAt: daysAgo(10),
    watchProgress: 30,
    watchedSeconds: 2736,
    totalSeconds: 9120,
    lastWatchedAt: daysAgo(4),
    fileSize: 10737418240,
  },

  // Comedy / Drama / Thriller
  {
    id: 'demo-5',
    imdbId: 'tt6751668',
    filename: 'Parasite.2019.1080p.mkv',
    filepath: '/demo/Parasite.2019.1080p.mkv',
    title: 'Parasite',
    year: '2019',
    genre: ['Comedy', 'Drama', 'Thriller'],
    plot: 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
    director: 'Bong Joon Ho',
    actors: 'Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong, Choi Woo-shik',
    imdbRating: '8.5',
    poster: 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
    type: 'movie',
    runtime: '132 min',
    rated: 'R',
    addedAt: daysAgo(14),
    watchProgress: 0,
    watchedSeconds: 0,
    totalSeconds: 7920,
    fileSize: 8053063680,
  },

  // Crime / Drama
  {
    id: 'demo-6',
    imdbId: 'tt0110912',
    filename: 'Pulp.Fiction.1994.1080p.mkv',
    filepath: '/demo/Pulp.Fiction.1994.1080p.mkv',
    title: 'Pulp Fiction',
    year: '1994',
    genre: ['Crime', 'Drama'],
    plot: 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
    director: 'Quentin Tarantino',
    actors: 'John Travolta, Uma Thurman, Samuel L. Jackson, Bruce Willis',
    imdbRating: '8.9',
    poster: 'https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
    type: 'movie',
    runtime: '154 min',
    rated: 'R',
    addedAt: daysAgo(20),
    watchProgress: 100,
    watchedSeconds: 9240,
    totalSeconds: 9240,
    watchedAt: daysAgo(10),
    fileSize: 9126805504,
  },

  // Animation / Family
  {
    id: 'demo-7',
    imdbId: 'tt0245429',
    filename: 'Spirited.Away.2001.1080p.mkv',
    filepath: '/demo/Spirited.Away.2001.1080p.mkv',
    title: 'Spirited Away',
    year: '2001',
    genre: ['Animation', 'Adventure', 'Family'],
    plot: 'During her family\'s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.',
    director: 'Hayao Miyazaki',
    actors: 'Daveigh Chase, Suzanne Pleshette, Miyu Irino, Rumi Hiiragi',
    imdbRating: '8.6',
    poster: 'https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
    type: 'movie',
    runtime: '125 min',
    rated: 'PG',
    addedAt: daysAgo(25),
    watchProgress: 0,
    watchedSeconds: 0,
    totalSeconds: 7500,
    fileSize: 7516192768,
  },

  // Drama / Western
  {
    id: 'demo-8',
    imdbId: 'tt1853728',
    filename: 'Django.Unchained.2012.1080p.mkv',
    filepath: '/demo/Django.Unchained.2012.1080p.mkv',
    title: 'Django Unchained',
    year: '2012',
    genre: ['Drama', 'Western'],
    plot: 'With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.',
    director: 'Quentin Tarantino',
    actors: 'Jamie Foxx, Christoph Waltz, Leonardo DiCaprio, Kerry Washington',
    imdbRating: '8.4',
    poster: 'https://image.tmdb.org/t/p/w500/7oWY8VDWW7thTzWh3OKYRkWAKdN.jpg',
    type: 'movie',
    runtime: '165 min',
    rated: 'R',
    addedAt: daysAgo(30),
    watchProgress: 0,
    watchedSeconds: 0,
    totalSeconds: 9900,
    fileSize: 11274289152,
  },

  // Horror
  {
    id: 'demo-13',
    imdbId: 'tt1457767',
    filename: 'The.Conjuring.2013.1080p.mkv',
    filepath: '/demo/The.Conjuring.2013.1080p.mkv',
    title: 'The Conjuring',
    year: '2013',
    genre: ['Horror', 'Mystery', 'Thriller'],
    plot: 'Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their farmhouse.',
    director: 'James Wan',
    actors: 'Patrick Wilson, Vera Farmiga, Ron Livingston, Lili Taylor',
    imdbRating: '7.5',
    poster: 'https://image.tmdb.org/t/p/w500/wVYREutTvI2tmxr6ujrHT704wGF.jpg',
    type: 'movie',
    runtime: '112 min',
    rated: 'R',
    addedAt: daysAgo(18),
    watchProgress: 0,
    watchedSeconds: 0,
    totalSeconds: 6720,
    fileSize: 7000000000,
  },

  // Romance / Drama
  {
    id: 'demo-14',
    imdbId: 'tt0109830',
    filename: 'Forrest.Gump.1994.1080p.mkv',
    filepath: '/demo/Forrest.Gump.1994.1080p.mkv',
    title: 'Forrest Gump',
    year: '1994',
    genre: ['Drama', 'Romance'],
    plot: 'The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75.',
    director: 'Robert Zemeckis',
    actors: 'Tom Hanks, Robin Wright, Gary Sinise, Sally Field',
    imdbRating: '8.8',
    poster: 'https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
    type: 'movie',
    runtime: '142 min',
    rated: 'PG-13',
    addedAt: daysAgo(22),
    watchProgress: 0,
    watchedSeconds: 0,
    totalSeconds: 8520,
    fileSize: 8500000000,
  },

  // ── TV Shows — Breaking Bad (S01, 7 episodes) ─────────────────────────────
  // The player's next-episode logic matches by title prefix + SxxExx in filename.
  // Having all 7 S01 episodes lets the "Up Next" / autoplay flow work end-to-end.

  {
    id: 'demo-bb-s01e01',
    imdbId: 'tt0903747',
    filename: 'Breaking.Bad.S01E01.1080p.mkv',
    filepath: '/demo/Breaking.Bad.S01E01.1080p.mkv',
    title: 'Breaking Bad',
    year: '2008',
    genre: ['Crime', 'Drama', 'Thriller'],
    plot: 'Chemistry teacher Walter White teams up with former student Jesse Pinkman to cook and sell crystal meth after being diagnosed with inoperable lung cancer.',
    director: 'Vince Gilligan',
    actors: 'Bryan Cranston, Aaron Paul, Anna Gunn, Dean Norris',
    imdbRating: '9.5',
    poster: 'https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg',
    type: 'series',
    runtime: '58 min',
    rated: 'TV-MA',
    addedAt: daysAgo(3),
    watchProgress: 100,
    watchedSeconds: 3480,
    totalSeconds: 3480,
    watchedAt: daysAgo(2),
    lastWatchedAt: daysAgo(2),
    fileSize: 3221225472,
    totalSeasons: 5,
    episodes: [
      { id: 'bb-s01e01', season: 1, episode: 1, title: 'Pilot', watched: true, watchedAt: daysAgo(2), runtime: '58 min', plot: 'Walter White, a struggling high school chemistry teacher, is diagnosed with inoperable lung cancer.' },
      { id: 'bb-s01e02', season: 1, episode: 2, title: 'Cat\'s in the Bag', watched: true, watchedAt: daysAgo(2), runtime: '48 min', plot: 'Walt and Jesse try to dispose of the bodies of Emilio and Krazy-8.' },
      { id: 'bb-s01e03', season: 1, episode: 3, title: 'And the Bag\'s in the River', watched: false, runtime: '48 min', plot: 'Walt must decide what to do with the captive Krazy-8.' },
      { id: 'bb-s01e04', season: 1, episode: 4, title: 'Cancer Man', watched: false, runtime: '48 min', plot: 'Walt tells his family about his cancer diagnosis.' },
      { id: 'bb-s01e05', season: 1, episode: 5, title: 'Gray Matter', watched: false, runtime: '48 min', plot: 'Walt and Skyler attend a party thrown by his former colleagues.' },
      { id: 'bb-s01e06', season: 1, episode: 6, title: 'Crazy Handful of Nothin\'', watched: false, runtime: '48 min', plot: 'Walt undergoes chemotherapy and Jesse tries to make a new drug connection.' },
      { id: 'bb-s01e07', season: 1, episode: 7, title: 'A No-Rough-Stuff-Type Deal', watched: false, runtime: '48 min', plot: 'Walt and Jesse try to steal methylamine from a warehouse.' },
    ],
  },
  {
    id: 'demo-bb-s01e02',
    imdbId: 'tt0903747',
    filename: 'Breaking.Bad.S01E02.1080p.mkv',
    filepath: '/demo/Breaking.Bad.S01E02.1080p.mkv',
    title: 'Breaking Bad',
    year: '2008',
    genre: ['Crime', 'Drama', 'Thriller'],
    plot: 'Walt and Jesse try to dispose of the bodies of Emilio and Krazy-8 while keeping their operation secret.',
    director: 'Adam Bernstein',
    actors: 'Bryan Cranston, Aaron Paul, Anna Gunn, Dean Norris',
    imdbRating: '9.5',
    poster: 'https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg',
    type: 'series',
    runtime: '48 min',
    rated: 'TV-MA',
    addedAt: daysAgo(3),
    watchProgress: 45,
    watchedSeconds: 1296,
    totalSeconds: 2880,
    lastWatchedAt: daysAgo(1),
    fileSize: 2684354560,
    totalSeasons: 5,
  },
  {
    id: 'demo-bb-s01e03',
    imdbId: 'tt0903747',
    filename: 'Breaking.Bad.S01E03.1080p.mkv',
    filepath: '/demo/Breaking.Bad.S01E03.1080p.mkv',
    title: 'Breaking Bad',
    year: '2008',
    genre: ['Crime', 'Drama', 'Thriller'],
    plot: 'Walt must make a life-or-death decision about the captive Krazy-8 while Jesse deals with the aftermath.',
    director: 'Adam Bernstein',
    actors: 'Bryan Cranston, Aaron Paul, Anna Gunn, Dean Norris',
    imdbRating: '9.5',
    poster: 'https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg',
    type: 'series',
    runtime: '48 min',
    rated: 'TV-MA',
    addedAt: daysAgo(3),
    watchProgress: 0,
    watchedSeconds: 0,
    totalSeconds: 2880,
    fileSize: 2684354560,
    totalSeasons: 5,
  },
  {
    id: 'demo-bb-s01e04',
    imdbId: 'tt0903747',
    filename: 'Breaking.Bad.S01E04.1080p.mkv',
    filepath: '/demo/Breaking.Bad.S01E04.1080p.mkv',
    title: 'Breaking Bad',
    year: '2008',
    genre: ['Crime', 'Drama', 'Thriller'],
    plot: 'Walt tells his family about his cancer diagnosis while Jesse reconnects with his parents.',
    director: 'Jim McKay',
    actors: 'Bryan Cranston, Aaron Paul, Anna Gunn, Dean Norris',
    imdbRating: '9.5',
    poster: 'https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg',
    type: 'series',
    runtime: '48 min',
    rated: 'TV-MA',
    addedAt: daysAgo(3),
    watchProgress: 0,
    watchedSeconds: 0,
    totalSeconds: 2880,
    fileSize: 2684354560,
    totalSeasons: 5,
  },

  // ── TV Shows — Stranger Things (S01, 8 episodes) ──────────────────────────

  {
    id: 'demo-st-s01e01',
    imdbId: 'tt4574334',
    filename: 'Stranger.Things.S01E01.1080p.mkv',
    filepath: '/demo/Stranger.Things.S01E01.1080p.mkv',
    title: 'Stranger Things',
    year: '2016',
    genre: ['Drama', 'Fantasy', 'Horror'],
    plot: 'When a young boy disappears, his mother, a police chief and his friends must confront terrifying supernatural forces in order to get him back.',
    director: 'Matt Duffer, Ross Duffer',
    actors: 'Millie Bobby Brown, Finn Wolfhard, Winona Ryder, David Harbour',
    imdbRating: '8.7',
    poster: 'https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg',
    type: 'series',
    runtime: '47 min',
    rated: 'TV-14',
    addedAt: daysAgo(12),
    watchProgress: 100,
    watchedSeconds: 2820,
    totalSeconds: 2820,
    watchedAt: daysAgo(10),
    lastWatchedAt: daysAgo(10),
    fileSize: 3758096384,
    totalSeasons: 4,
    episodes: [
      { id: 'st-s01e01', season: 1, episode: 1, title: 'The Vanishing of Will Byers', watched: true, watchedAt: daysAgo(10), runtime: '47 min', plot: 'On his way home from a friend\'s house, young Will sees something terrifying.' },
      { id: 'st-s01e02', season: 1, episode: 2, title: 'The Weirdo on Maple Street', watched: true, watchedAt: daysAgo(9), runtime: '55 min', plot: 'Lucas, Mike and Dustin try to talk to the girl they found in the woods.' },
      { id: 'st-s01e03', season: 1, episode: 3, title: 'Holly, Jolly', watched: false, runtime: '51 min', plot: 'An increasingly concerned Joyce makes a startling discovery.' },
      { id: 'st-s01e04', season: 1, episode: 4, title: 'The Body', watched: false, runtime: '55 min', plot: 'Refusing to believe Will is dead, Joyce tries to connect with her son.' },
      { id: 'st-s01e05', season: 1, episode: 5, title: 'The Flea and the Acrobat', watched: false, runtime: '52 min', plot: 'Hopper breaks into the lab while Nancy and Jonathan devise a plan.' },
      { id: 'st-s01e06', season: 1, episode: 6, title: 'The Monster', watched: false, runtime: '46 min', plot: 'Eleven\'s past is revealed. Nancy and Jonathan are in danger.' },
      { id: 'st-s01e07', season: 1, episode: 7, title: 'The Bathtub', watched: false, runtime: '41 min', plot: 'Eleven tries to contact Will and Barbara in the Upside Down.' },
      { id: 'st-s01e08', season: 1, episode: 8, title: 'The Upside Down', watched: false, runtime: '54 min', plot: 'Dr. Brenner\'s men close in on the lab. Joyce and Hopper enter the Upside Down.' },
    ],
  },
  {
    id: 'demo-st-s01e02',
    imdbId: 'tt4574334',
    filename: 'Stranger.Things.S01E02.1080p.mkv',
    filepath: '/demo/Stranger.Things.S01E02.1080p.mkv',
    title: 'Stranger Things',
    year: '2016',
    genre: ['Drama', 'Fantasy', 'Horror'],
    plot: 'Lucas, Mike and Dustin try to talk to the mysterious girl they found in the woods. Joyce receives a call from Will.',
    director: 'Matt Duffer, Ross Duffer',
    actors: 'Millie Bobby Brown, Finn Wolfhard, Winona Ryder, David Harbour',
    imdbRating: '8.7',
    poster: 'https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg',
    type: 'series',
    runtime: '55 min',
    rated: 'TV-14',
    addedAt: daysAgo(12),
    watchProgress: 20,
    watchedSeconds: 660,
    totalSeconds: 3300,
    lastWatchedAt: daysAgo(6),
    fileSize: 3900000000,
    totalSeasons: 4,
  },
  {
    id: 'demo-st-s01e03',
    imdbId: 'tt4574334',
    filename: 'Stranger.Things.S01E03.1080p.mkv',
    filepath: '/demo/Stranger.Things.S01E03.1080p.mkv',
    title: 'Stranger Things',
    year: '2016',
    genre: ['Drama', 'Fantasy', 'Horror'],
    plot: 'An increasingly concerned Joyce makes a startling discovery about Will. Hopper investigates the lab.',
    director: 'Matt Duffer, Ross Duffer',
    actors: 'Millie Bobby Brown, Finn Wolfhard, Winona Ryder, David Harbour',
    imdbRating: '8.7',
    poster: 'https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg',
    type: 'series',
    runtime: '51 min',
    rated: 'TV-14',
    addedAt: daysAgo(12),
    watchProgress: 0,
    watchedSeconds: 0,
    totalSeconds: 3060,
    fileSize: 3600000000,
    totalSeasons: 4,
  },

  // ── TV Shows — Game of Thrones (S01, 3 episodes for variety) ─────────────

  {
    id: 'demo-got-s01e01',
    imdbId: 'tt0944947',
    filename: 'Game.of.Thrones.S01E01.1080p.mkv',
    filepath: '/demo/Game.of.Thrones.S01E01.1080p.mkv',
    title: 'Game of Thrones',
    year: '2011',
    genre: ['Action', 'Adventure', 'Drama'],
    plot: 'Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.',
    director: 'David Benioff, D.B. Weiss',
    actors: 'Emilia Clarke, Peter Dinklage, Kit Harington, Lena Headey',
    imdbRating: '9.2',
    poster: 'https://image.tmdb.org/t/p/w500/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg',
    type: 'series',
    runtime: '62 min',
    rated: 'TV-MA',
    addedAt: daysAgo(8),
    watchProgress: 100,
    watchedSeconds: 3720,
    totalSeconds: 3720,
    watchedAt: daysAgo(5),
    lastWatchedAt: daysAgo(5),
    fileSize: 4294967296,
    totalSeasons: 8,
    episodes: [
      { id: 'got-s01e01', season: 1, episode: 1, title: 'Winter Is Coming', watched: true, watchedAt: daysAgo(5), runtime: '62 min', plot: 'Lord Eddard Stark is asked by the King to serve as the Hand of the King.' },
      { id: 'got-s01e02', season: 1, episode: 2, title: 'The Kingsroad', watched: false, runtime: '56 min', plot: 'The Starks head south as Daenerys tries to adjust to her new life.' },
      { id: 'got-s01e03', season: 1, episode: 3, title: 'Lord Snow', watched: false, runtime: '58 min', plot: 'Jon Snow arrives at the Wall. Ned discovers a disturbing secret.' },
      { id: 'got-s01e04', season: 1, episode: 4, title: 'Cripples, Bastards, and Broken Things', watched: false, runtime: '56 min', plot: 'Ned investigates Jon Arryn\'s death. Tyrion visits the Wall.' },
      { id: 'got-s01e05', season: 1, episode: 5, title: 'The Wolf and the Lion', watched: false, runtime: '55 min', plot: 'Catelyn has captured Tyrion. Ned discovers the truth about Jon Arryn.' },
    ],
  },
  {
    id: 'demo-got-s01e02',
    imdbId: 'tt0944947',
    filename: 'Game.of.Thrones.S01E02.1080p.mkv',
    filepath: '/demo/Game.of.Thrones.S01E02.1080p.mkv',
    title: 'Game of Thrones',
    year: '2011',
    genre: ['Action', 'Adventure', 'Drama'],
    plot: 'The Stark family heads south while Daenerys tries to adjust to life with the Dothraki.',
    director: 'Tim Van Patten',
    actors: 'Emilia Clarke, Peter Dinklage, Kit Harington, Lena Headey',
    imdbRating: '9.2',
    poster: 'https://image.tmdb.org/t/p/w500/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg',
    type: 'series',
    runtime: '56 min',
    rated: 'TV-MA',
    addedAt: daysAgo(8),
    watchProgress: 0,
    watchedSeconds: 0,
    totalSeconds: 3360,
    fileSize: 4000000000,
    totalSeasons: 8,
  },

  // ── TV Shows — Rick and Morty (single entry, no next-ep needed) ───────────

  {
    id: 'demo-12',
    imdbId: 'tt2861424',
    filename: 'Rick.and.Morty.S01E01.1080p.mkv',
    filepath: '/demo/Rick.and.Morty.S01E01.1080p.mkv',
    title: 'Rick and Morty',
    year: '2013',
    genre: ['Animation', 'Adventure', 'Comedy'],
    plot: 'An animated series that follows the exploits of a super scientist and his not-so-bright grandson.',
    director: 'Justin Roiland, Dan Harmon',
    actors: 'Justin Roiland, Chris Parnell, Spencer Grammer, Sarah Chalke',
    imdbRating: '9.1',
    poster: 'https://image.tmdb.org/t/p/w500/cvhNj9eoRBe5SxjCbQTkh05UP5K.jpg',
    type: 'series',
    runtime: '23 min',
    rated: 'TV-14',
    addedAt: daysAgo(15),
    watchProgress: 0,
    watchedSeconds: 0,
    totalSeconds: 1380,
    fileSize: 1073741824,
    totalSeasons: 7,
    episodes: [
      { id: 'rm-s01e01', season: 1, episode: 1, title: 'Pilot', watched: false, runtime: '23 min', plot: 'Rick moves in with his daughter\'s family and takes Morty on an adventure.' },
      { id: 'rm-s01e02', season: 1, episode: 2, title: 'Lawnmower Dog', watched: false, runtime: '22 min', plot: 'Rick and Morty enter people\'s dreams. Snuffles the dog gains intelligence.' },
      { id: 'rm-s01e03', season: 1, episode: 3, title: 'Anatomy Park', watched: false, runtime: '22 min', plot: 'Rick and Morty go inside a homeless man\'s body to save a theme park.' },
    ],
  },
];

export default function handler(_req: Request, res: Response) {
  res.json(DEMO_ITEMS);
}
